# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: bulma-clean-theme
title: ElectroCode
email: iota@electrocode.net
description: |-
  ElectroCode is a blog about technology, programming, and electronics.
  It covers a wide range of topics including software development, hardware design, and the latest trends in the tech industry.
  The blog features tutorials, reviews, and insights from the author's personal experiences in the field.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://electrocode.net" # the base hostname & protocol for your site
twitter_username: ecodein
github_username:  ElectroCode
name: ElectroCode
author: IotaSpencer
year: 2025
my_age: 34

#related_project_keys: ["technology", "gem"]
skip_related_projects: true

# host for serving locally and viewing with my phone

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
repository: IotaSpencer/electrocode.net
#   #####                                
#  #     #  ####   ####  #   ##   #      
#  #       #    # #    # #  #  #  #      
#   #####  #    # #      # #    # #      
#        # #    # #      # ###### #      
#  #     # #    # #    # # #    # #      
#   #####   ####   ####  # #    # ###### 
share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true
  reddit: false
social:
  github: ElectroCode
  gitlab: ElectroCode
  twitter: ecodein
  youtube: "@ElectroCode"
  bluesky: "@ElectroCode"
  tel: "1-408-782-4682"

  rss: feed.xml

#      #                    
#     # #              ##
#    #   #    # ##       # 
#   #######   ##  #   ####     
#  #       #  #   #  #   #            
# #         # #   #  #####            
# Google Analytics key, leave blank to ignore
google_analytics: G-KBTS96Y63V
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 
  shortname: electrocodenet
comments: false
permalink: pretty
# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
timezone: America/New_York
sass:
  silence_deprecations: ['import']
  quiet_deps: true
sass_dir: _sass/
autopages:
  enabled: true
# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
pagination:
  enabled: true
  # The number of posts to show per page
  per_page: 3
  permalink: /page/:num/
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
timezone: America/New_York
exclude: ["README.md", "LICENSE", "vendor/", "node_src", "*.map", ".gitignore", ".idea/", ".vscode/",
  "Gemfile*", "*.gemspec", ".sass-cache", "_resume.html", ".jekyll-cache", ".jekyll-metadata",
   ".DS_Store", "node_modules/", "package-lock.json", "yarn.lock", ".venv/", "bin/", "_old_dirs/"]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
  - jekyll-paginate-v2
#defaults:
#  -
#    scope:
#      path: "projects"
#      type: "pages"
#    values:
#      layout: "project"
#      author: "Mr. Hyde"
#      category: "project"
